name: CI

on: [Master
    release/*branches]
    pull_request:
      branches:
        - master
    schedule:
    _cron:"0 2 * * 1-5"      

jobs:
  build:deploy to staging

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Greatings to you,
        
        echo test, and deploy your project.
